export const ARRAY_PROJECTS = [
  {
    img: '/assets/project/img-project-1.png',
    title: 'Cvfree',
    description: 'Free online curriculum vitae',
    tech: 'react typescript tailwind recoil node express mongodb',
    github: 'https://github.com/autoclickvn/cvfree',
    imgDemo: '/assets/project/img-demo-cvfree.webp',
    linkDemo: 'http://cvfree.top',
  },
  {
    img: '/assets/project/img-project-3.png',
    title: 'Cvfree App',
    description: 'Free online curriculum vitae on mobile app',
    tech: 'react react-native typescript redux formik',
    github: 'https://github.com/autoclickvn/cvfree-mobile-app',
    imgDemo: '/assets/project/img-demo-cvfree-mobile.webp',
    linkDemo: 'https://youtu.be/Tmjgf6rKoCc',
  },
  {
    img: '/assets/project/img-project-3.png',
    title: 'CMS Base',
    description: 'A basic CMS framework',
    tech: 'react tailwind typescript redux formik',
    github: 'https://github.com/autoclickvn/cms-base',
    imgDemo: '/assets/project/img-demo-cms-base.webp',
    linkDemo: 'https://base-cms.herokuapp.com',
  },
  {
    img: '/assets/project/img-project-4.png',
    title: 'Galaxy Utility',
    description: 'A repository of utility functions',
    tech: 'typescript npm',
    github: 'https://github.com/autoclickvn/galaxy-utility',
    imgDemo: '/assets/project/img-demo-galaxy-utility.webp',
    linkDemo: 'https://www.npmjs.com/package/galaxy-utility',
  },
  {
    img: '/assets/project/img-project-1.png',
    title: 'Weather',
    description: 'See Vietnam weather with weather web app',
    tech: 'react css',
    github: 'https://github.com/autoclickvn/weather-app',
    imgDemo: '/assets/project/img-demo-weather.webp',
    linkDemo: 'https://vn-weather.herokuapp.com',
  },
  {
    img: '/assets/project/img-project-3.png',
    title: 'Cards Game',
    description: 'Tien Len Mien Bac',
    tech: 'react bootstrap antdesign ',
    github: 'https://github.com/autoclickvn/cards-game',
    imgDemo: '/assets/project/img-demo-cards-game.webp',
    linkDemo: 'https://tienlenmienbac.herokuapp.com',
  },
];
