export const ARRAY_PROJECTS = [
  {
    img: '/assets/project/img-project-1.png',
    title: 'Cvfree',
    description: 'PROJECT.DES_1',
    tech: 'react typescript tailwind recoil node express mongodb',
    github: 'https://github.com/autoclickvn/cvfree',
    imgDemo: '/assets/project/img-demo-cvfree.webp',
    linkDemo: 'http://cvfree.top',
  },
  {
    img: '/assets/project/img-project-3.png',
    title: 'Cvfree App',
    description: 'PROJECT.DES_2',
    tech: 'react react-native typescript redux formik',
    github: 'https://github.com/autoclickvn/cvfree-mobile-app',
    imgDemo: '/assets/project/img-demo-cvfree-mobile.webp',
    linkDemo: 'https://youtu.be/Tmjgf6rKoCc',
  },
  {
    img: '/assets/project/img-project-3.png',
    title: 'CMS Base',
    description: 'PROJECT.DES_3',
    tech: 'react tailwind typescript redux formik',
    github: 'https://github.com/autoclickvn/cms-base',
    imgDemo: '/assets/project/img-demo-cms-base.webp',
    linkDemo: 'https://base-cms.herokuapp.com',
  },
  {
    img: '/assets/project/img-project-4.png',
    title: 'Galaxy Ultra UI',
    description: 'PROJECT.DES_4',
    tech: 'nextjs tailwind typescript',
    github: '',
    imgDemo: '/assets/project/img-demo-galaxy-ultra.webp',
    linkDemo: 'https://galaxyultra.net',
  },
  {
    img: '/assets/project/img-project-1.png',
    title: 'Weather',
    description: 'PROJECT.DES_5',
    tech: 'react css',
    github: 'https://github.com/autoclickvn/weather-app',
    imgDemo: '/assets/project/img-demo-weather.webp',
    linkDemo: 'https://vn-weather.herokuapp.com',
  },
  {
    img: '/assets/project/img-project-3.png',
    title: 'Cards Game',
    description: 'PROJECT.DES_6',
    tech: 'react bootstrap antdesign ',
    github: 'https://github.com/autoclickvn/cards-game',
    imgDemo: '/assets/project/img-demo-cards-game.webp',
    linkDemo: 'https://tienlenmienbac.herokuapp.com',
  },
];
